### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by pbinkley** [datasittersclub/site#30]
I notice that some links on the public site are breaking: there are links to a different entry that use this form: ```https://datasittersclub.github.io/site/dsc4/```, but the target pages are actually served with this form: ```https://datasittersclub.github.io/site/dsc4.html```. I assume this was because of a change in the config (but I haven't checked). Example: in [DSC#6](https://datasittersclub.github.io/site/dsc6.html), in paragraph 3, the link to DSC#4 points to ```https://datasittersclub.github.io/site/dsc4/``` when it should point to ```https://datasittersclub.github.io/site/dsc4.html```

**Comment by pbinkley** [comment]
If it would save trouble to have a pull request with a big search-and-replace to fix these links, I'd be proud to have a chance to contribute, if someone would point me to the right directory to do it in, since I don't know my way around how the site is rendered

**Comment by quinnanya** [comment]
Thank you! We switched from Jekyll to JupyterBook at some point, and clearly I didn't catch all the path changes! The source code for the site is [here](https://github.com/datasittersclub/site/tree/master/site); then I re-generate the static pages on my machine and push it to the branch that gets served.
